title: pliniewicz
email: patryk@tfwno.gf
description: >- 
  Descriptions are boring. This is just current version of my homepage.
baseurl: "" 
url: "" 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
