<?php include_once("analyticstracking.php") ?>
<div align="center"><h2>Astrotrip 2013</h2></div>
<span class="data">Autor notki: Dajana Olech</span><br><br>
<center><iframe src="//player.vimeo.com/video/72385136?portrait=0&amp;color=ff9933" width="550" height="309" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></center>

<br><br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Niedziela, 21 lipca 2013, godzina 14:00,
<br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Obserwatorium Astronomiczne Uniwersytetu Jagiellońskiego
<br><br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/1.JPG" border="0"><img src="img/astrotrip2013/1m.JPG" align="left" style="margin-right: 10px;" title="Pakowanie Żukiety"></a>Studenci Naukowego Koła Studentów Astronomii UJ gorączkowo się krzątają przy ich Żuku. Trzy osoby (Skurowski, Dolech i Paluina) upychają, rozkładają, składają ponownie… Biedny pojazd musi udźwignąć 7 osób, ich bagaże, sprzęt obserwacyjny, namioty, śpiwory, jedzenie, piłki, hamaki, rzutnik multimedialny, karimaty, latarki, butle gazowe, kuchenny stuff, itd. To wymaga dobrego zagospodarowania przestrzennego każdego centymetra Czerwonej Strzały. Ale spoko – delikwenci maja tydzień, żeby to opanować, dadzą radę!
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kiedy Żuk zostaje wypchany, studenci wsiadają i machając na pożegnanie portierowi i Miśce, opuszczają teren  Obserwatorium.  Nie ma odwrotu, przed nimi do przebycia ponad 1000km pojazdem, który liczy sobie 21 wiosenek.  Na szczęście na pokładzie, ba, nawet za jego kierownicą mamy Pierwszego Mechanika Żuka  - prezesa - Sebastiana Kurowskiego.  To on w razie „w”, będzie go reanimował przy wsparciu duchowym reszty grupy.
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/2.JPG" border="0"><img src="img/astrotrip2013/2m.JPG" align="right" style="margin-left: 10px;" title="Nad Jeziorem Rożnowskim"></a>Jeszcze w Krakowie trzeba zgarnąć Janusza i Kingę, zrobić mega zapas konserw, pasztetów i zupek chińskich i  w liczbie 5 osób, studenci ruszają w stronę Jeziora Rożnowskiego, tu spędzą pierwszą noc wyprawy. Samochód od pierwszych chwil sprawuje się nad wyraz dobrze, mimo sprzęgła na granicy wytrzymałości. Mknąc na południe, uczestnicy AstroTripa podziwiają coraz to nowe i piękniejsze widoki. Po dotarciu na miejsce i zakrojonych na szeroką skalę poszukiwaniach dobrego miejsca, rozbijają obóz nad jeziorem. Po odcykaniu pierwszej setki zdjęć na każdym aparacie rozpalają ognisko i cieszą się spektakularna pogonią Wenus za Słońcem, w stronę horyzontu.  Po pierwszej „integracji” (nie żeby nie byli już zintegrowani), pora na pierwsze obserwacje tej podróży! Kołowicze zacierają ręce – ale będziemy obserwować..! I wtem dzieje się coś, czego nikt się nie spodziewał, studenci przecierają oczy ze zdumienia i w głębokim szoku przerzucają wzrok od swoich przerażonych twarzy na niebo i z powrotem. To co się odgrywa na nieboskłonie woła o pomstę do nieba! Tuż nad drzewami skrada się jak złodziej wielki, ogromny, oślepiający Księżyc w pełni! Nie no, każdy wiedział, że wyjdzie wypinając pierś, ale przy tak malym sztucznym zaświetleniu nieba, to było niemal jak zbrodnia. Studenci, szybko dostosowując się do zaistniałej sytuacji, wyciągają aparaty i zaczynają sesję zdjęciową naszego jedynego Satelity. Kładą się częściowo w Żuku, a częściowo w namiocie z pięknym widokiem na jezioro, z myślą, że za chwilę będą musieli wstawać, by wspiąć się na pobliskie wzgórze i zobaczyć wschód Słońca. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/3.JPG" border="0"><img src="img/astrotrip2013/3m.JPG" align="left" style="margin-right: 10px;" title="Malowniczy zachód Księżyca"></a>Mimo, że budzik dzwoni o morderczej, 4 godzinie i za nic nie chce się wstać,  uczestnicy wyprawy śpiący w namiocie, jakimś cudem otwierają oczy. To, co się im ukazuje przywraca chęci i siły by wstać. Nad taflą jeziora i wzgórz nad nim górujących, za horyzont chowa się ten, co nabroił tyle w nocy – Księżyc. Tak pięknego jego zachodu dawno nie widzieli!  Studentom udaje się złożyć namiot zostawiając jedynie materac i śpiwory i obudzić resztę wycieczki. Ci jednak po pierwszych oznakach przytomności umysłu idą dalej spać. Cóż więc robić? Osamotniona dwójka rozpoczyna zatem heroiczną wspinaczkę pod górę przez mokrą trawę, wysokie zboże, płoty i cudze posesje próbując za bardzo nie narażać się miejscowym psom. Tuż przy szczycie, już totalnie przemoczeni robią jeszcze kilka fotek pięknym widokom na pobliskie wzgórza oraz jezioro i już mogą podziwiać wschodzące pomiędzy drzewami Słoneczko. W drodze powrotnej przekonują się, że wzdłuż trasy, jaka przemierzyli w drodze do góry, biegnie całkiem sucha i przyjemna jezdnia. Ale, jak to mówi Prezes „fak de system”! Po powrocie jeszcze chwilka spania, (pozostali kołowicze starają się zadbać o to, by to faktycznie była chwilka) i można zbierać manatki i wyruszać po kolejnych dwóch uczestników AstroTripa do Nowego Sącza. Po drodze Żuk mija Wolę Kurowską, w której obowiązkowo trzeba zrobić kilka zdjęć. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/4.JPG" border="0"><img src="img/astrotrip2013/4m.JPG" align="right" style="margin-left: 10px;" title="W drodze przez Dolinę Popradu"></a>W Nowym Sączu dołączają Michał i Patryk. Pod Żukiem uginają się koła, kiedy chłopaki pokazują ilość bagaży. Jednak po pierwszym przerażeniu okazuje się, że nie taki diabeł straszny i na siłę udaje się upchać ostatnie plecaki. Już z kompletem na pokładzie pojazd się kieruje w stronę Doliny Popradu. Widoki zapierają dech w piersiach! Konieczny zatem wydaje się postój, obiad i szybka mini-kąpiel nad jedną z rzek. Po odpoczynku od odpoczynku zostaje ustalony kolejny cel – Klimkówka i tamtejsze jezioro. Podczas jazdy, okazuje się, że możliwe, iż strome podjazdy przechytrzą Żuczesława, ale frajer ten, kto zwątpił w poczciwy pojazd! Mimo ciężkich chwil, dzięki wsparciu duchowym całego tyłu Żuka, udaje się pokonać nawet te najbardziej oporne i wredne góry. Jezioro Klimkówka okazuje się całkiem przyjemnym jeziorkiem, w którym fajnie się topi koleżanki w ubraniach. No i fajnie się mąci nimi wodę… Próba dokończenia czwartej setki zdjęć i hop do auta kierującego się tym razem do Grybowa, gdzie Kingi rodzina w sposób błyskawiczny zarówno przeprowadziła akcję promocyjną pokazów nieba Koła, jak i po prostu przekonała burmistrza, że to świetna okazja dla mieszkańców, by się czegoś nowego dowiedzieć. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/8.JPG" border="0"><img src="img/astrotrip2013/8m.JPG" align="left" style="margin-right: 10px;" title="Pokazy na Rynku w Grybowie"></a>Wieczorem wycieczka dociera do domu rodzinnego Kingi, gdzie zostaje ugoszczona serdecznymi uśmiechami, a także pyszną kawą i kolacją. Kiedy pojawia się pan Księżyc, studenci wiedzą, że muszą się zbierać na pierwsze pokazy nocne na grybowski rynek. Jednym z odwiedzających jest sam burmistrz!  Po ochach i achach przy Celestronie (takim fajnym teleskopie), czas wrócić do domu Kingi, gdzie studenci spędzą kolejną noc. Ale najpierw rozstawiają krzesła obok siebie (chyba chcą poczuć się, jak w kinie)  i wpatrzeni w nocne niebo jeszcze długo siedzą i rozmawiają przy świetle Księżyca. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nad ranem wszystkich budzi zapach świeżej kawy i przepysznego śniadania. I budziki, bo przecież trzeba zdążyć na kolejne pokazy, z tym, że tym razem Słońca. Tu, zainteresowanie, przerosło oczekiwania chyba wszystkich. Do godziny 14 rynek odwiedza tyle osób wspierających finansowo zakup paliwa do Żuka, że ten może ujechać kolejne 100km gratis. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/5.JPG" border="0"><img src="img/astrotrip2013/5m.JPG" align="right" style="margin-left: 10px;" title="Bieszczadzka Andromeda"></a>Ciężka praca podczas pokazów zostaje wynagrodzona cudownym obiadem zrobionym przez mamę Kingi. Uczestnicy podróży ani nie chcą ani nie mogą się ruszyć, by spakować manatki i wyruszyć w stronę Bieszczad. Ale jak trzeba to trzeba. Po drodze kilka postojów na uzupełnienie zapasów żywieniowych i można witać znak Roztoki Górne, gdzie niegdyś mieściła się zamiejscowa stacja obserwacyjna Uniwersytetu Jagiellońskiego. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Początkowo ciężko jest trafić na odpowiednią polanę, ale po rozmowie z leśniczym-komandosem i przetestowaniu niezawodnego węchu Prezesa, udaje się dotrzeć do chatki schowanej pomiędzy drzewami. Tam, już po ciemku, studenci rozbijają obóz, w pierwszej kolejności rozstawiając teleskopy. Zmienność bieszczadzkich temperatur daje się we znaki chyba wszystkim, ale opracowany plan „nachuchania” do namiotów o dziwo się sprawdza i koło godziny 4, po dostatecznym nacieszeniu oczu gwiazdami, wszyscy zasypiają. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/6.JPG" border="0"><img src="img/astrotrip2013/6m.JPG" align="left" style="margin-right: 10px;" title="Obóz w Bieszczadach"></a>Pobudkę wyznacza Słońce – w namiotach robi się zwyczajnie duszno. Jednak za dużo było tego chuchania. Po tzw. śniadaniu, dziewczyny wyciągają koce i olejki do opalania, a chłopaki teleskopy, piłki, itp. Popołudniu 4 delikwentów udaje się Żukiem do Cisnej, do sklepu, z sebastianowymi butami na dachu pojazdu (buty przetrwały!). Po powrocie jeszcze kilka fotek zachodzącego Słoneczka, kąpiel w strumyczku, który chyba tak naprawdę powinien mieć stan stały i można rozpalać obozowego Super-Grilla i świętować imieniny Kingi nietypowym tortem z serka Valbon. Po odśpiewaniu i odtańczeniu przez chłopaków specjalnych, dedykowanych numerów, wysłuchaniu strasznych historii i kilku spojrzeniach w niebo, trzeba iść spać – wcześnie rano pobudka!
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ostatnego poranka w Bieszczadach nikt nie zauważa, bo wszyscy słodko śpią, Jedynie świadomość tego, że zaspali, motywuje ekipę do wyczołgania się z namiotów i rozpoczęcia pakowania/przygotowywania śniadania/powzięcia czynności związanych z doprowadzaniem swojej twarzy i ubioru do ładu, czyli tzw. „ogarniania się“. Dochodząc już do wprawy w smarowaniu chleba pasztetem i konserwą, śniadanie i pakowanie przebiega sprawnie. Ciężko jest pożegnać się astronomom z tak wspaniałym miejscem z przepięknymi widokami.  Na trasę, w stronę Jeziora Solińskiego, Żuk wyjeżdża ok. 14:00. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/7.JPG" border="0"><img src="img/astrotrip2013/7m.JPG" align="right" style="margin-left: 10px;" title="Nad Jeziorem Solińskim"></a>Nad jeziorkiem, okazuje się, że z powodu dużego zainteresowania ludzi akurat plażą Żukersów, nie bardzo jest możliwość by zwyczajnie wyciągnąć szampony do włosów oraz żele pod prysznic i zacząć się myć, więc pomysłowi astronomowie wynajmują rowerki wodne, by podpłynąć w miejsce większego zagęszczenia roślin – potocznie zwanego „krzakami“. Tu, wykorzystując zgoła odmienne techniki, każdemu udaje się coś tam zdziałać, by poprawić swój wygląd zewnętrzny (tzn. zeskrobać zewnętrzną warstwę brudu), a potem wszyscy kieruja swoje pojazdy w kierunku niesamowitych skał wpadających wprost do jeziora. Wszyscy dobrze wiedzą, że po tak wyczerpującej czynności należy się oczywiście dobrze posilić więc już „czyści” i „pachnący” zamawiają przepyszne i przezdrowe kebaby, itp. Mimo, ze kazano głodnym bardzo długo czekać, panowie laskawie decydują się wybaczyć kelnerce jej średnie ogarnięcie, bo, jak mówią, „jest ładna“. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/9.JPG" border="0"><img src="img/astrotrip2013/9m.JPG" align="left" style="margin-right: 10px;" title="Bojówki NKSA pod zamkiem w Krasiczynie"></a>W celu uzupełnienia zapasów pasztetów, trzeba zahaczyć o Lesko i tamtejsze Tesco (ale się fajnie zrymowało! :D – przyp. tł.). szybko, bo się ściemnia, a przed dotarciem na Zamojszczyznę trzeba jeszcze wstąpić do Krasiczyna, gdzie czeka piękny zameczek.
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jak na złość, podczas zwiedzania padają wszystkie aparaty fotograficzne. Chyba jednak trzeba było oszczędzać akumulatory, a nie fotografować wesoły autobus przez cała drogę...
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Do Górecka (małej wioski, w której znajduje się malutki 200-letni domek rodziny jednej z uczestniczek AstroTripa), wycieczka wjeżdża juz w nocy. Tam czeka na nich dodatkowa grupa kołowiczów. Szybka akcja z rozpakowywaniem i już można rozpalać grilla. Tak oraz wojną na szyszki z Roztoczańskiego Parku Narodowego  czy zwyzywaniem huby na drzewie mija czas i wszyscy się kładą tuż przed wschodem Słońca. Obserwacje może lepiej zostawić na następną noc...
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/10.JPG" border="0"><img src="img/astrotrip2013/10m.JPG" align="right" style="margin-left: 10px;" title="Poranne obserwacje w Górecku"></a>Wczesnym-rankiem-przed-południem, kiedy to osoby z problemami ze snem budzą wszystkich innych i następuje ogólny chaos, najwięksi zapaleńcy wyciagają teleskpy, by podziwiać piękne wybuchy na Słońcu. Tego dnia są gigantyczne! Szybka wizyta w sklepie pani Joli, śniadanie i cała jedenastka wyrusza do Zwierzyńca – miasteczka oddalonego o jakieś 8km (pod warunkiem, że całą drogę idzie się przez las). Tu zahacza o Stawy Echa, gdzie odgrywają, już tradycyjnie, mistrzostwa gry w piłkę wodną, a potem kieruje się do kościólka na wodzie i gospody „Młyn“. Tu natomiast okazuje się, że rozstawiono mini-parkiet i można potańczyć więc nie tracąc czasu, część studentów rusza na jego podbój. Droga powrotna mija już w całkowitej ciemności. I bardzo głośnym śpiewie. Wszyscy chyba się cieszą, że po dotarciu do chatki rozstawią teleskopy i dokonają kolejnej części badań nad zaśmieceniem świetlnym nocnego nieba w południowej części Polski. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/11.JPG" border="0"><img src="img/astrotrip2013/11m.JPG" align="left" style="margin-right: 10px;" title="Objadamy się szczypami, czy jak to się pisze..."></a>Nad ranem, osoby śpiace w Żuku budzi trzęsienie ziemi. Nie da się opisać inaczej tego, co robi pozostała część grupy ostatnim śpiącym, zataczając się ze śmiechu. Po litościwym rozpatrzeniu wniosku o „jeszcze 5 minut“, następuje kolejne podczas tej wyprawy pakowanie. Dziś Czerwona Strzała musí dotrzeć do Rzepiennika Biskupiego, gdzie swoje obserwatorium astronomiczne buduje dr Bogdan Wszołek. Przy wyjeźdździe z Górecka koniecznie trzeba jeszcze kupić cebularze i już można rozwijać zastraszające prędkośći w kierunku Sanu, gdzie panowie zamierzają się wykąpać. I wcale ich nie odstraszają zdechłe ryby na brzegu...
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Po drodze na południe, kołowicze odwiedzają kolejny pałac, tym razem w Łańcucie. Na teren „Bogdanówki“ wjeżdżają juz o zmroku. Miłe i serdeczne powitanie państwa Wszołek oraz śpiewy przy ognisku kończą kolejny, pełen wrażeń dzień. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/12.JPG" border="0"><img src="img/astrotrip2013/12m.JPG" align="right" style="margin-left: 10px;" title="Pałac w Łańcucie"></a>Ostatniego dnia, podczas pobytu gospodarzy na mszy, uczestnicy wyprawy, zbierają bób, na obiad. Po ich powrocie, wszyscy razem wybierają się do obserwatorium, gdzie znajduje się radioteleskop oraz dwie kopuły. Są one na razie puste, co studenci próbowali zmienić, ale po pierwszych sukcesach przy złożeniu teleskopów, okazuje się, że brakuje niezbędnych śrubek i ostateczny montaż trzeba nieco przesunąć w czasie. Caly dzień mija bardzo przyjemnie przy nieustannych opowieściach doktora o współczesnej astronomii, dawnych studiach astronomii na UJocie i róznych instrumentach badawczych. Doktor proponuje Kołu również współpracę i przedstawia swoje plany dotyczące wkładu w polską astronomię. Tak więc z wielkimi postanowieniami, kończy sie ostatní etap Wielkiego AstroTripa 2013. Żegnając państwa Wszołek, Żuk kieruje swoje koła na Kraków i tamtejsze Obserwatorium Astronomiczne, gdzie będzie odpoczywał aż do następnej wyprawy. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/13.JPG" border="0"><img src="img/astrotrip2013/13m.JPG" align="left" style="margin-right: 10px;" title="Rzepiennickie bóby :P"></a>Cały wyjazd okazał się niezwykle kształcący dla wszystkich. Każdy pasażer Żuka przekonał się na przykład, że kiedy w pojeździe znajdują się średnio zrównoważeni psychicznie studenci, niezbędne są pasy bezpieczeństwa. Powszechnie także już wiadomo, że kierowca powinien zaopatrzyć się przed podróżą w stopery do uszu ze względu na próby spełniania się wokalnie kołowiczów. No, chyba, że jak Prezes, sam też chce się tak spełniać...
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nie tylko uczestnicy wyprawy nauczyli się czegoś nowego. Pani Jola ze sklepu w Górecku, już teraz wie, że kiedy przyjeżdża NKSA, hurtowo trzeba zamawiać cebularze, rodzice Kingi następnym razem zastanowią się, czy aby na pewno chcą zapraszać wiecznie głodnych studentów do swojego domu, a DJ ze Zwierzyńca przekonał się, że powinien zmienić tekst w jednej ze swoich piosenek z „ole, ole“ na „dolech, dolech“.
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="img/astrotrip2013/14.JPG" border="0"><img src="img/astrotrip2013/14m.JPG" align="right" style="margin-left: 10px;" title="Obserwatorium Astronomiczne dra Bogdana Wszołka"></a>Wyprawa okazała się wielkim sukcesem oraz swoistym przetarciem szlaków dla następnych. Zarówno Żuk, jak i kołowicze zdali test na wytrzymałość, zatem za rok, pojazd będzie musiał pokonać dużo dłuższą trasę – plany już są! Atmosfera zarówno w Żuku, jak i poza nim była niepowtarzalna, a ekipa okazała się zgrana i gotowa na wiele. Jeszcze przez długi czas każdy z uczestników będzie wspominał przeżycia z tych wspaniałych 8 dni wspomagając swoją pamięć tysiącami zrobionych podczas wyprawy zdjęć i filmików.
<br><br>
<a href="https://plus.google.com/photos/102348230098260093243/albums/5909101207271097585?banner=pwa">Galeria zdjęć z wyprawy.</a>

