<?php include_once("analyticstracking.php") ?>
<?php define('TITLE', 'Warsztaty astrofotograficzne w Obserwatorium Astronomicznym na Lubomirze'); ?>

<h3>Warsztaty astrofotograficzne w Obserwatorium Astronomicznym na Lubomirze</h3>
<span class="data">Autor: Sebastian Kurowski, 15 kwietnia 2014 r.</span><br><br>

<center><iframe width="560" height="315" src="//www.youtube.com/embed/d3Ivs4dXkf4" frameborder="0" allowfullscreen></iframe></center>

<br><br>
<p>
<a href="img/lub1d.jpg" border="0"><img src="img/lub1.jpg" align="right" style="margin-left: 10px;" width="40%" title="Wyruszamy"></a>&nbsp;&nbsp;&nbsp;12&nbsp;kwietnia 2014, godzina 16:00. Pod budynkiem Instytutu Fizyki UJ stacjonuje rzucający się w&nbsp;oczy, tajemniczy, czerwony pojazd, a&nbsp;wokół niego krząta się grupa wyjątkowo rozchichotanych ludzi. Czyżby to był wóz strażacki? Może jakiś van wyprodukowany przez Ferrari? A&nbsp;może po prostu jakiś niezidentyfikowany pojazd poruszający się z&nbsp;olbrzymią prędkością i&nbsp;przez to obdarzony gigantycznym redshiftem? Jak się okazuje, wszystkie odpowiedzi są po części prawdziwe – rzeczywiście jest to pojazd strażacki, obdarzony silnikiem o&nbsp;ogromnej mocy, ze znaczkiem przypominającym znaczek Ferrari (tylko z&nbsp;kozłem zamiast konia) i&nbsp;potrafiący rozwijać prędkości o&nbsp;jakich nie śniło się fizykom. Jest to Żuk, a&nbsp;dodając do tego fakt, że stoi on pod Instytutem Fizyki, to ludzie dookoła muszą być... No tak, zaczynają włazić na dach i&nbsp;się cieszą – to muszą być astronomowie. Rozpoczyna się kolejna epicka wyprawa Naukowego Koła Studentów Astronomii, tym razem na południe, do Obserwatorium Astronomicznego na Lubomirze.
</p>
<br>
<p>
<a href="img/lub2d.jpg" border="0"><img src="img/lub2.jpg" align="left" style="margin-right: 10px;" width="40%" title="Zmieniamy środek transportu"></a>&nbsp;&nbsp;&nbsp;Godzina 16:30 – wyruszamy. Pędzimy z&nbsp;zawrotną prędkością, stojąc w&nbsp;korku. Ledwo wyruszyliśmy, a&nbsp;już boimy się czy starczy nam paliwa aby dokulać się do najbliższej stacji. Rozpoczyna się dramatyczna walka z&nbsp;czasem. Zdążymy, czy może zostaniemy z&nbsp;unieruchomionym, ponad dwutonowym Żukiem na środku Alei? Żuk powoli posuwa się do przodu metr za metrem, z&nbsp;każdą chwilą pożerając kolejne mililitry (a&nbsp;może raczej hektolitry :P) paliwa. Po pół godziny niepewności wreszcie docieramy do stacji. Już chwilę później wrzucamy czwórkę i &nbsp;pędzimy Zakopianką, dzielnie pokonując wzniesienia i&nbsp;zakręty. Na pace naszej Czerwonej Strzały jak zwykle panuje doskonała atmosfera. Latają piłeczki antystresowe, Pavlo zabawia wszystkich niezwykłymi sztuczkami magicznymi (jak on to robi?!), a&nbsp;Dajana nieskutecznie próbuje rzucić się z&nbsp;okna Żuka, nagrywając wszystko GoPro. <a href="img/lub3d.jpg" border="0"><img src="img/lub3.jpg" align="right" style="margin-left: 10px;" width="40%" title="Szczytowanie"></a>Po pewnym czasie, zjeżdżamy z&nbsp;dwupasmówki, a&nbsp;kilka kilometrów dalej rozpoczyna się kręta, wąska, dziurawa, aczkolwiek malownicza droga. Później nawet dziury znikają, bo nie ma asfaltu, w&nbsp;którym mogłyby się robić. Jak się okazuje, Żukiecie niestraszne są trudne górskie warunki typu offroad i&nbsp;szybko docieramy na miejsce. Teraz bagaże na barki, padają hasła: „Po co ja tego tyle napakowałem/am?” i&nbsp;ruszamy szlakiem zwieńczonym u&nbsp;szczytu budynkiem obserwatorium. Brawa dla Bożeny, która pomimo kontuzji dzielnie znosi trudy podejścia.
</p>
<br>
<p>
<a href="img/lub4d.jpg" border="0"><img src="img/lub4.jpg" align="left" style="margin-right: 10px;" width="40%" title="Zapracowani :P"></a>&nbsp;&nbsp;&nbsp;Na górze przyjmuje nas dyrektor obserwatorium - Marcin Cikała. Jeszcze nie zdążył do końca wyrzucić z&nbsp;pamięci naszej ostatniej wizyty, podczas której wykazaliśmy się nadzwyczajnym pracoholizmem, a&nbsp;już znowu ma nas na głowie. Rozlokowujemy się w&nbsp;pokojach, chwila oddechu i&nbsp;bierzemy się do pracy – w&nbsp;końcu po to tu przyjechaliśmy! Tematem przewodnim tegorocznych warsztatów jest astrofotografia. Marcin Cikała jest w&nbsp;tym mistrzem (o&nbsp;czym można się przekonać chociażby oglądając zdjęcia na stronie OA na Lubomirze: <a href="http://obserwatorium.lubomir.weglowka.pl/index.php?option=com_content&view=article&id=27&Itemid=45">link</a>), więc nie mogliśmy lepiej trafić. Cierpliwie tłumaczy nam tajniki udanej astrofotografii, poczynając od wstępnej redukcji danych, aż po wyciąganie subtelnych szczegółów ze zdjęć. Przekonujemy się, że obróbka danych jest niezwykle czasochłonna. Chcąc uzyskać udane zdjęcie należy wykazać się nie tylko ogromną cierpliwością (niejednokrotnie trzeba zaczynać pracę od samego początku, chcąc uzyskać lepszy efekt), ale również dbałością o&nbsp;szczegóły oraz naturalność zdjęcia.
</p>
<br>
<p>
<a href="img/lub5d.jpg" border="0"><img src="img/lub5.jpg" align="right" style="margin-left: 10px;" width="40%" title="Teleskop PlaneWave"></a>&nbsp;&nbsp;&nbsp;W&nbsp;międzyczasie powoli poprawia się pogoda, aż w&nbsp;końcu nad Lubomirem ukazuje się piękne, czyste niebo. Udajemy się więc pod kopułę teleskopu – wspinamy się wąskimi krętymi schodami i&nbsp;po chwili naszym oczom ukazuje się piękny instrument – 17-calowy astrograf firmy PlaneWave, na pancernym montażu paralaktycznym. Otwieramy kopułę, wszystko jest już praktycznie gotowe do obserwacji i... mamy problem z&nbsp;kamerą CCD, która nie odpowiada. Po długich próbach zdiagnozowania problemu, setkach kursów na trasie kopuła-sterownia, niestety musimy się poddać. Być może jeszcze nie jesteśmy gotowi na obserwacje pięknego lubomirskiego nieba (podczas poprzednich warsztatów zawsze padało). No cóż – jesteśmy cierpliwi i&nbsp;uparci, więc jeszcze z&nbsp;pewnością nie raz spróbujemy oszukać przeznaczenie. <a href="img/lub6d.jpg" border="0"><img src="img/lub6.jpg" align="left" style="margin-right: 10px;" width="40%" title="Lubomirskie niebo"></a>Pozostałą część nocy spędzamy na dalszych pracach przy komputerach. Procesory się grzeją, mózgi parują (no dobra, z&nbsp;mózgami przegiąłem :P), a&nbsp;na ekranie każdego z&nbsp;komputerów powoli pojawia się coraz piękniejszy obraz galaktyki M51. Marcin wykazuje się ogromną cierpliwością co chwilę podchodząc do każdego z&nbsp;nas i&nbsp;rozwiązując nasze „trudne sprawy” przy obróbce. Około godziny piątej nad ranem, gdy powoli zaczynamy ślinić klawiatury laptopów, postanawiamy odpocząć i&nbsp;pójść spać, z&nbsp;mocnym postanowieniem pobudki o jedenastej (czy naprawdę ktokolwiek wierzył, że to się uda?).
</p>
<br>
<p>
<a href="img/lub7d.jpg" border="0"><img src="img/lub7.jpg" align="right" style="margin-left: 10px;" width="40%" title=""></a>&nbsp;&nbsp;&nbsp;Pomińmy o&nbsp;której niektórzy, w&nbsp;tym autor tego tekstu, wstali kolejnego dnia. Istotne jest to, że po szybkim ogarnięciu się i&nbsp;zjedzeniu śniadania (lub obiadu – zależy od przyjętej definicji śniadania) przystąpiliśmy do dokańczania naszych zdjęć. Niestety około godziny 16:00 nasz czas minął i&nbsp;trzeba było powoli zacząć zbierać się w&nbsp;drogę powrotną. Jednak półtora dnia warsztatów to zdecydowanie za mało jak na tak skomplikowaną dziedzinę jaką jest astrofotografia. Podczas wielu godzin spędzonych przy komputerach udało nam się uzyskać całkiem przyzwoite zdjęcia, jednak wciąż czarno-białe. Planujemy już kolejne warsztaty, tym razem trzydniowe, na których mamy nadzieję na większe szczęście przy obserwacjach oraz podczas których poznamy kolejne etapy powstawania pięknych kolorowych zdjęć Wszechświata. Tymczasem postaramy się szlifować zdobyte dotychczas umiejętności u&nbsp;nas, w&nbsp;Obserwatorium w&nbsp;Krakowie. Miejmy nadzieję, że pogoda dopisze i&nbsp;wkrótce nasza galeria poszerzy się o&nbsp;ładne zdjęcia galaktyk i&nbsp;mgławic.
</p>
<br>
<p>
<a href="img/lub8d.jpg" border="0"><img src="img/lub8.jpg" align="left" style="margin-right: 10px;" width="40%" title="Dolech się wietrzy"></a>&nbsp;&nbsp;&nbsp;Około godziny 19:00 docieramy do Krakowa. Żuk w&nbsp;drodze powrotnej, tak jak poprzednio, spisuje się doskonale. Udaje nam się nawet wyprzedzić jakiś autobus oraz jednego vana i&nbsp;to pod górkę! Już nam tęskno za jazdą Żukiem. Miejmy nadzieję, że wkrótce znowu nadarzy się okazja do jakiegoś epickiego astro-wyjazdu.
</p>
<br>
<p>
&nbsp;&nbsp;&nbsp;Ogromnie dziękujemy Marcinowi Cikale za przyjęcie nas na Lubomirze, wielką cierpliwość oraz podzielenie się tajnikami sztuki astrofotografii. Z&nbsp;niecierpliwością czekamy na kontynuację warsztatów :)
</p>
<br>
<p>
<a href="https://plus.google.com/photos/102348230098260093243/albums/6002162055054099313?banner=pwa">Galeria zdjęć z&nbsp;wyjazdu.</a>
</p>
