<?php include_once("analyticstracking.php") ?>
<div align="center"><h2> Projekt Grubb</h2></div>
<span class="data">Autor notki: Sebastian Kurowski</span><br><br>
 <p><img src="img/grubb.jpg" align="right" style="margin-left: 10px;" width="40%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Projekt ma na celu renowację zabytkowej lunety Grubba z 1874 roku oraz przystosowanie jej do obserwacji Słońca. Początkowo planowane jest prowadzenie regularnych obserwacji z wykorzystaniem filtra z folii mylarowej, a w dalszej perspektywie za pomocą filtru H-alpha.
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Luneta Grubb początkowo umieszczona w kopule zachodniej obserwatorium w Collegium Śniadeckiego, obecnie znajduje się w budynku na południowo-zachodnim krańcu Obserwatorium UJ na Skale. Początkowo głównie wykorzystywana do badania gwiazd zmiennych zaćmieniowych, po przeniesieniu na Skałę powoli traciła na znaczeniu i stawała się coraz bardziej zapomniana. Okazyjnie wykorzystywana o obserwacji amatorskich lub pokazów nieba niszczała aby wreszcie, w 2009 roku, studenci astronomii postanowili przywrócić ją do dawnej świetności.
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Grubb jest to refraktor o średnicy 8 cali, umieszczony na montażu paralaktycznym z grawitacyjnym napędem zegarowym. Oznacza to, że sama luneta do pracy nie potrzebuje prądu, ponieważ napędzana jest opadającym piętro niżej ciężarem na linie. Przed każdymi obserwacjami należy, za pomocą korby mocowanej z boku postumentu, podnieść ciężar na maksymalną wysokość, a następnie zwolnić blokadę mechanizmu. Równomierne tykanie dochodzące z montażu świadczy o gotowości lunety do pracy. Niewielka dźwignia przy przekładniach pozwala na zmianę prędkości śledzenia z gwiazowej na księżycową. Dodatkowo Grubb wyposażony jest w niezwykłą celownicę z tubusem wykonanym w całości z drewna. Przez lata użytkowania lunecie zaaplikowane zostały liczne przeróbki takie jak podświetlenie skali w kącie godzinnym i deklinacji, szukacz w postaci lunety PZO, elektryczne mikroruchy i wiele innych. Naszym celem jest przywrócenie lunety do stanu początkowego, czyli pozbawienie jej tych wszystkich zbędnych "gadżetów".
<p><img src="img/s3.jpg" align="right" style="margin-left: 10px;" width="40%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Projekt nieoficjalnie rozpoczął się już w 2009 roku. Wtedy jednak awaria zasilania w kopule wstrzymała wszystkie prace aż do końca roku akademickiego. Końcem czerwca 2010 roku, dzięki pomocy Grzegorza Sęka z Młodzieżowego Obserwatorium Astronomicznego w Niepołomicach, udało się wykonać pierwsze zdjęcia Słońca z wykorzystaniem filtra H-alpha wypożyczonego z MOA oraz kamery CCD. Efekty okazały się bardzo zachęcające. Początkiem 2011 roku projekt nabrał rozpędu. Przystąpiliśmy do czyszczenia kopuły i teleskopu oraz wstępnego czyszczenia drobnych elementów za pomocą pasty polerskiej. Powoli naszym oczom ukazywały się lśniące elementy wykończenia Grubba, co skutecznie zachęciło nas do dalszej pracy.
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Zakup filtru H-alpha wiąże się z dużym wydatkiem, a nam zależy na jak najszybszym rozpoczęciu regularnych obserwacji Słońca, więc zdecydowaliśmy się na zamotnowanie tymczasowego filtra w postaci folii mylarowej. Wkrótce ustalone zostaną dyżury obserwacyjne, aby od nowego roku akademickiego wykorzystać każdy pogodny dzień na obserwacje. W międzyczasie teleskop zostanie przygotowany do demontażu celem gruntownego czyszczenia i malowania. 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wszelkie pytania odnośnie projektu można kierować na adres:
<a href="mailto:astrojohny@nac.uj.edu.pl">astrojohny@nac.uj.edu.pl</a> lub <a href="mailto:skurowski@byk.oa.uj.edu.pl">skurowski@byk.oa.uj.edu.pl</a>.
<br><br>
<center><img src="img/s2.jpg" width="95%"></center>
<br>
<p>Linki:
<br>- <a href="https://picasaweb.google.com/nksauj/SOnceWHAlpha">Testowe zdjęcia Słońca w H-alpha.</a>
<br>- <a href="https://picasaweb.google.com/nksauj/SOnce">Testowe zdjęcia Słońca z filtrem mylarowym.</a>
<br>- <a href="https://picasaweb.google.com/nksauj/RefraktorGrubb">Zdjęcia Grubba.</a>
<br>- <a href="http://www.arm.ac.uk/history/instruments/Grubb-10inch.html">Inny Grubb po renowacji.</a>


