<?php include_once("analyticstracking.php") ?>
<?php define('TITLE', 'WKW'); ?>

<h3>Konferencja Naukowo-Badawcza Wrocław-Kraków-Warszawa</h3>
<span class="data">Autor: Dajana Olech, 28 kwietnia 2012 r.</span><br><br>

<p>
&nbsp;&nbsp;&nbsp;Zarządzeniem Prezesa, wszyscy mieliśmy się spotkać o&nbsp;5:15 na Dworcu Głównym w&nbsp;Krakowie, w&nbsp;celu odbycia wspólnej podróży na kolejne z&nbsp;cyklu "Spotkanie Trzech Kół Naukowych" (rok 2012, tym razem wydawnictwo UWr.). Planowany odjazd pociągu zakrawał o&nbsp;godzinę szóstą więc nawet sam Sebastian nie pojawił się tak wcześnie (w&nbsp;przeciwieństwie np. do Błażeja Szulca - :D). Przedziały okazały się puste więc każdy spokojnie mógł się jeszcze zdrzemnąć. Z&nbsp;okazji skorzystali tylko nieliczni gdyż, jak to zwykle bywa, znalazł się "szurnięty przedział", któremu nie w&nbsp;głowie był odpoczynek, a&nbsp;wręcz przeciwnie. Dowiedzieć się można było np. kto z&nbsp;kim był ostatnio widziany w&nbsp;Obserwatorium, kto nie zdał MMFiA, kto komu nie pożyczył notatek, kto biegnie na pociąg w&nbsp;Katowicach i&nbsp;pewnie nie dobiegnie, a&nbsp;także kto ma pirackiego WinRARa, czy którego września rozpoczyna się część właściwa sesji, tzw. "kampania wrześniowa".
</p>
<br>
<p>
<a href="img/wkw1d.jpg" border="0"><img src="img/wkw1.jpg" align="right" style="margin-left: 10px;" width="40%" title="Na wrocławskim rynku"></a>&nbsp;&nbsp;&nbsp;Po 5-godzinnej podróży (która mogła skończyć się tragicznie, gdyż Paulina Sowicka zamiast "piorunów" widziała strzałki pokazujące dostęp do prądu - kontakt), dotarliśmy na miejsce, tj. Dworzec Główny we Wrocławiu, gdzie czekali już na nas Ula Kaszubkiewicz oraz Paweł Biernacki. Poniosło nas aż do hostelu "Absynt", gdzie mieliśmy spędzić pierwszą noc Konferencji. Jak się okazało, nocowały tam tylko nasze torby, ale o&nbsp;tym później. Lżejsi o&nbsp;jakieś 30 kg ruszyliśmy na obiad. Po nim, ciężsi o&nbsp;jakieś <img src=img/nieczytelne.png>&nbsp;kg, zebraliśmy się na spotkanie z astronomami ze Stolicy, którzy od dłuższego czasu siedzieli na wrocławskim Rynku kontemplując piękno... piwnic tamtejszych zabudowań. <a href="img/wkw2d.jpg" border="0"><img src="img/wkw2.jpg" align="left" style="margin-right: 10px;" width="40%" title="Wykład o Izerskim Parku Ciemnego Nieba"></a>Dołączyliśmy do nich zafascynowani niesamowitymi wykończeniami ścian, po czym po pierwszej (tego dnia) integracji, zostaliśmy odprowadzeni do Instytutu Astronomii UWr, gdzie dr Sylwester Kołomański opowiedział o&nbsp;"Izerskim Parku Ciemnego Nieba" (tak, Drodzy Uczestnicy, wykład był właśnie o&nbsp;tym - Piotrek "Bażant" Sobestiańczuk ma nawet notatki - zdecydowanie obowiązkowa lektura!).
</p>
<br>
<p>
&nbsp;&nbsp;&nbsp;Po powrocie z&nbsp;"Kopernika", niesamowicie się ociągając, udało nam się ogarnąć i&nbsp;z&nbsp;minimalnym poślizgiem dotarliśmy na miejsce kolejnej integracji. Tu, nie zapominając, że to konferencja astronomiczna, sokami wznosiliśmy toasty za kurs analizy na pierwszym roku na UJocie, a&nbsp;także za dalszą współpracę Kół. Do motywów astronomicznych można także zaliczyć wschodzące Słońca w&nbsp;drodze powrotnej do hostelu.
</p>
<br>
<p>
<a href="img/wkw3d.jpg" border="0"><img src="img/wkw3.jpg" align="right" style="margin-left: 10px;" width="40%" title="Prezentacja Barta Stratosferycznego"></a>&nbsp;&nbsp;&nbsp;Kilka chwil spania i&nbsp;nastał ten moment, kiedy to trzeba było wyruszyć na pierwszą sesję referatową - "Heliofizyka" do Instytutu Fizyki Uniwersytetu Wrocławskiego, którą otworzył dr Tomasz Mrozek, który wygłosił referat na temat Słońca. Później można było usłyszeć o&nbsp;tym "Jak zmierzyć odległość do Słońca" Przemka Mroza, o&nbsp;"Badaniach wpływu Słońca na atmosferę Ziemi za pomocą balonu stratosferycznego" Barta Wiadomojakiego oraz o&nbsp;"Strukturach chromosferycznych" Dominika Kunce, a&nbsp;jeszcze przed przerwą obiadową wysłuchaliśmy Adama Ciesielskiego z&nbsp;jego "Wyprawą na zaćmienie".
</p>
<br>
<p>
<a href="img/wkw4d.jpg" border="0"><img src="img/wkw4.jpg" align="left" style="margin-right: 10px;" width="40%" title="Pod budynkiem UWr. w drodze na obiad"></a>&nbsp;&nbsp;&nbsp;Kiedy już wszyscy wrócili z&nbsp;błogimi uśmiechami na twarzach, rozpoczęliśmy drugi blok referatowy - "Zmienność w&nbsp;astronomii". Popołudniową sesję rozpoczął dr Zbigniew Kołaczkowski z&nbsp;"Fotometrią satelitarną". Następnie swoją prezentację przedstawił Paweł Biernacki, w&nbsp;której zawarł "Zmiennośc widmową gwiazdy neutronowej RX J0720.4-3125". Moja prezentacja o&nbsp;"Refraktorze Grubba" była niestety słabo widoczna ze względu na duże zanieczyszczenie światłem, ale już Maksa Sokołowskiego pt. "Chodź pomaluj mój świat" wyszła bardzo dobrze. <a href="img/wkw5d.jpg" border="0"><img src="img/wkw5.jpg" align="right" style="margin-left: 10px;" width="40%" title="Teleskop Cassegraina w Białkowie"></a>Jak to powiedział Paweł, zamknęliśmy sesję "z&nbsp;wysokiego c" wykładem Marka Zwierza, który mówił o&nbsp;"Kosmologii". Po zakończeniu prezentacji, pokusiliśmy się o&nbsp;przejrzenie zdjęć z&nbsp;dnia poprzedniego. Nasze życie już nigdy nie będzie takie samo... Po chwili przyjechał autokar, który zabrał nas do stacji obserwacyjnej w&nbsp;Białkowie. Tu, po "rozpakowaniu" chętni mogli przejść do reflektora Cassegraina, część w&nbsp;dalszym ciągu odpoczywała, a&nbsp;jeszcze inni przygotowywali prezentacje, które miały być wygłoszone na następny dzień. <a href="img/wkw6d.jpg" border="0"><img src="img/wkw6.jpg" align="left" style="margin-right: 10px;" width="40%" title="Integracja przy ognisku"></a>Wkrótce przyszedł Paweł, który oznajmił, że zapanował już nad ogniem i&nbsp;można piec kiełbaski, czy co tam kto miał. Wieczór minął w&nbsp;przyjemnej atmosferze (pełnej dwutlenku węgla) i&nbsp;wśród rozmów posilaliśmy się pysznym jedzeniem, które przygotowali Wrocławianie, a&nbsp;którego z&nbsp;pewnością zazdrościłby nam każdy normalny student.
</p>
<br>
<p>
<a href="img/wkw7d.jpg" border="0"><img src="img/wkw7.jpg" align="right" style="margin-left: 10px;" width="40%" title="Gra w kalambury"></a>&nbsp;&nbsp;&nbsp;Po jakimś czasie, kiedy to z&nbsp;Pauliną wracałyśmy do pokoju w&nbsp;celach spoczynkowych, spotkałyśmy Sebastiana, Błażeja oraz Bażanta, którzy podążali w&nbsp;kierunku światła, ale słowo "ciastka" spowodowało zmianę zwrotu ich wektora przemieszczenia, przy zachowaniu jego kierunku. W&nbsp;jednym z&nbsp;pokojów poczyniliśmy przygotowania do gry w&nbsp;kalambury, które nadzorowała Kasia Wierzbicka ze względu na ich nietypową formę, która miała ułatwić zgadywanie takich haseł, jak "dyski akrecyjne z&nbsp;niestandardową lepkością", <a href="img/wkw8d.jpg" border="0"><img src="img/wkw8.jpg" align="left" style="margin-right: 10px;" width="40%" title="Przysmaki od Wrocławiaków"></a>"wariancja estymatora wariancji", "wielkie twierdzenie Fermata", "oświetlenie skali kąta godzinnego Maksutova" czy "nawalona Wenus po urodzinach Słońca". Tak spędziliśmy czas do niemalże świtu, aż w&nbsp;końcu wpakowaliśmy się do łóżek przewidując kolejny, ciężki poranek.
</p>
<br>
<p>
&nbsp;&nbsp;&nbsp;Rano, po jakichś dwóch godzinach od pierwszej pobudki, którą wyznaczył prof. Rudawy swoim przybyciem, kiedy już wszyscy ocknęli się na tyle, żeby utrzymać się na nogach bez niczyjej pomocy, udaliśmy się do koronografu, gdzie Profesor opowiedział ze szczegółami o&nbsp;jego działaniu. <a href="img/wkw9d.jpg" border="0"><img src="img/wkw9.jpg" align="right" style="margin-left: 10px;" width="40%" title="Prof. Rudawy opowiada o koronografie"></a>Po save'ie wszystkich bajtów informacji (liczonch raczej w&nbsp;Giga) o&nbsp;urządzeniu, wysłuchaliśmy prezentacji o&nbsp;Słońcu.
</p>
<br>
<p>
&nbsp;&nbsp;&nbsp;Czas był niemiłosierny i&nbsp;jego względność obróciła się przeciw nam więc kolejny, ostatni blok referatów "Działalność poszczególnych kół naukowych", który rozpoczął Sebastian, kontynuowała Basia Handzlik, a&nbsp;zakończyła Ula, minął szybko i&nbsp;trzeba było ruszać w&nbsp;drogę powrotną.
</p>
<br>
<p>
<a href="img/wkw10d.jpg" border="0"><img src="img/wkw10.jpg" align="left" style="margin-right: 10px;" width="40%" title="Prezentacja o NKSA"></a>&nbsp;&nbsp;&nbsp;Udało nam się dotrzeć do Wrocławia zgodnie z&nbsp;planem (zakładaliśmy przybycie na godzinę piętnastą plus-minus 2h). Wpakowaliśmy się do pociągu i&nbsp;rozpoczęliśmy ostatnią część drogi powrotnej do domu. W&nbsp;trasie, wbrew wcześniejszym groźbom, nikt z&nbsp;nas nie spał, a&nbsp;wręcz przeciwnie. Dyskusja rozgorzała na dobre. Została ona tylko raz brutalnie przerwana zapanowaniem całkowitej ciemności, ale szybko dostosowaliśmy się do zaistniałej sytuacji ciesząc się jak dzieci i&nbsp;rozpoczęliśmy opowieści o&nbsp;strasznych wydarzeniach. Po kilku minutach stężenie fotonów w&nbsp;powietrzu wróciło do normy, a&nbsp;my wróciliśmy do żartów. Do Krakowa dotarliśmy na godzinę przed północą zakańczając wspólną podróż.<a href="img/wkw11d.jpg" border="0"><img src="img/wkw11.jpg" align="right" style="margin-left: 10px;" width="40%" title="Powrót do Krakowa"></a>
</p>
<br>
<p>
&nbsp;&nbsp;&nbsp;Kolejny etap współpracy trzech Kół Naukowych dobiegł końca zapoczątkowując następny, nowy. Z&nbsp;pewnością nie ostatni.
</p>
